package util

import java.awt.Point
import java.awt.Rectangle
import kotlin.random.Random
import kotlin.test.*

class TwoDTreeMapTest {
   @Test fun testRandomInsertsAndDeletes() {
      val tree = TwoDTreeMap<String>()
      val contentMap = HashMap<Point, String>()
      fun doInsert() {
         val value = Random.nextString(50)
         val point = Point(Random.nextInt(-100, 101), Random.nextInt(-100, 101))
         val result = tree.insert(point.x, point.y, value)
         assertEquals(contentMap.contains(point), !result, "insert item")
         contentMap[point] = value
         println("tree.insert(${point.x}, ${point.y}, \"$value\")")
      }
      fun doDelete() {
         val key = contentMap.keys.random()
         println("tree.delete(${key.x}, ${key.y})")
         assertTrue(tree.delete(key.x, key.y), "delete item")
         contentMap.remove(key)
      }

      repeat(100) {
         doInsert()
      }

      repeat(1000) {
         val doInsert = Random.nextBoolean() || contentMap.isEmpty()
         if (doInsert) {
            if (Random.nextBoolean()) {
               // insert duplicate
               val point = contentMap.keys.random()
               val newValue = Random.nextString(10)
               assertFalse(tree.insert(point.x, point.y, newValue), "insert duplicate key - return false")
               assertEquals(newValue, tree.findAny(point.x .. point.x, point.y .. point.y), "insert duplicate key - updated value")
            } else
               doInsert()
         } else if (Random.nextBoolean()) {
            // delete real
            doDelete()
         } else {
            // delete fake
            val random = Point(Random.nextInt(-100, 101), Random.nextInt(-100, 101))
            if (contentMap.contains(random))
               random.x = 1000
            assertFalse(tree.delete(random.x, random.y),"delete item not in tree")
         }
      }
   }

   @Test fun testFindAny() {
      val tree = TwoDTreeMap<String>()
      val contentMap = HashMap<Point, String>()
      fun doInsert() {
         val value = Random.nextString(50)
         val point = Point(Random.nextInt(-100, 101), Random.nextInt(-100, 101))
         contentMap[point] = value
         tree.insert(point.x, point.y, value)
         println("tree.insert(${point.x}, ${point.y}")
      }

      repeat(100) {
         doInsert()
      }

      repeat(1000) {
         var start = Random.nextInt(-100, 101)
         val width = Random.nextInt(1, 102 - start)
         val xRange = IntRange(start, start + width - 1)
         start = Random.nextInt(-100, 101)
         val height = Random.nextInt(1, 102 - start)
         val yRange = IntRange(start, start + height - 1)
         val result = tree.findAny(xRange, yRange)
         println("FIND $xRange $yRange")
         val rect = Rectangle(xRange.start, yRange.start, width, height)
         val validValues = contentMap.entries.filter { rect.contains(it.key.x, it.key.y) }.map { it.value }
         if (validValues.isEmpty())
            assertNull(result, "tree should not have found anything")
         else
            assertContains(validValues, result, "got a valid entry")
      }

   }

   @Test fun testFindAll() {
      val tree = TwoDTreeMap<String>()
      val contentMap = HashMap<Point, String>()
      fun doInsert() {
         val value = Random.nextString(50)
         val point = Point(Random.nextInt(-100, 101), Random.nextInt(-100, 101))
         contentMap[point] = value
         tree.insert(point.x, point.y, value)
         println("tree.insert(${point.x}, ${point.y}, \"$value\")")
      }

      repeat(100) {
         doInsert()
      }

      repeat(1000) {
         var start = Random.nextInt(-100, 101)
         val width = Random.nextInt(1, 102 - start)
         val xRange = IntRange(start, start + width - 1)
         start = Random.nextInt(-100, 101)
         val height = Random.nextInt(1, 102 - start)
         val yRange = IntRange(start, start + height - 1)
         val result = tree.findAll(xRange, yRange)
         println("FIND $xRange $yRange")
         val rect = Rectangle(xRange.start, yRange.start, width, height)
         val validValues = contentMap.entries.filter { rect.contains(it.key.x, it.key.y) }.map { it.value }
         assertEquals(validValues.toSet(), result.toSet(), "didn't have set of expected values")
      }
   }

   @Test fun ass() {
      val tree = TwoDTreeMap<String>()
      tree.insert(-4, -32, "bshhoccexupradpajcbjqeqvgmqmouaegjwgrpvamvcocekzrb")
      tree.insert(-4, 60, "xkvnxvfhstekqnkalmqwpzlvsedkawyilizqjokkdxizbkardw")
      tree.insert(-1, 74, "xlbtedxrycjpinacyiiemgqmtivqpsomqgugjtezetazlokkob")
      tree.insert(-32, -16, "knfsplxootampbkamurczxxjvursothyavvakukgaagugbkxbn")
      tree.insert(74, -73, "hvmaqoavxtvxecyqiumhtbcaaxfovkaifmmwsrsnsnxvwficri")
      tree.insert(-5, -84, "xnepwmrftazxraceakilkekanxngzoohmejjvqstheidzejhge")
      tree.insert(-95, 59, "loxhncvddpxocllypogrqxacundovixhkxlnzdinzawsybhltt")
      tree.insert(-99, 24, "loitmfdoriaeyzahbiklyyouivsatnkvvasxivcjduvfbpgrie")
      tree.insert(60, 15, "qbsbnfqbabkjkbjbnztkkrhboykdcrhowmbgldsttsaxffnwyn")
      tree.insert(-21, -55, "oqxuatsrfifkredraetodflehsrrlvidcsbcberrzhssnlyoux")
      tree.insert(53, -54, "smgoozlxezdigshwyqveclqecvbkmndtvjpxfbdqepwicpxnxp")
      tree.insert(93, -4, "uycskaiaoryswlurwhmbscpyukjzrzzfexkzcbeptlplhlxkor")
      tree.insert(-61, 8, "xgfvocchoiwoesnnmqxlkrtqtiloytikzcmnremduzhpnikeug")
      tree.insert(38, -44, "ocqipyppkgognqgezxzdadqlsbkgjxykniulfymjybpiaibdfz")
      tree.insert(-82, -83, "jgeaorknsjeymvsgxblprbecddqxmngdqdjtbmscwvsyqaogxf")
      tree.insert(32, -86, "ihkrwhjphbuwpwmqygkqvgepvouyjzdrusgamjvaqiwzwyhhpp")
      tree.insert(3, -26, "vvwfrtdjguuyjisslramsjhllianqolijxkqnemjxxpwgltkqh")
      tree.insert(98, -29, "whwmtgfpuodlimwfimtvmpuelabjrrgxatlwnvekgibyvonyyp")
      tree.insert(68, 4, "gqrrqumlcxsonifpnlbtecwnkvpacwhjiuqteohpeypxowyqoe")
      tree.insert(88, -81, "cgrtjgpubcoagvgbmikeyfwxysewqwofpdwqhqrtsgdbnpmtfy")
      tree.insert(-58, -69, "grtbsmluxbkgdgutiduovzfftyybedbajuqzqozylwrhvwfrbv")
      tree.insert(-88, 40, "soxweycizeyicxqaabzchttspnckgzbfhpdyplmkpuvnhngmsc")
      tree.insert(-34, 17, "pcimoecltthiiontrdmesgdkzbibuvnkzpzbjliabejwflzoty")
      tree.insert(-20, 16, "inpgphkbvzelptnqffktyfdsihfhmxcqpqpknjagbnrhwulqys")
      tree.insert(47, -19, "hbmflizjsfwqwzbnuglydeksercsoreytwpxfunknymyxmhofo")
      tree.insert(48, 84, "pgmiughuneujoodsmjwwgfjtiwcdfzrvcsitjeilawqdbffzkn")
      tree.insert(90, -40, "bduybokpdcatpvxezjgcpwzabtlghgtobwhgrrddzxjbwjault")
      tree.insert(-77, 67, "upxumtwzusjembsaathnpyznrgzpfctmghynmsqlnsjaiukils")
      tree.insert(69, -1, "narqmhkuvbbdcziwjctabwiddlhzpsgueowsbjeplhicrirlxp")
      tree.insert(25, -71, "yogfagelkyerdsxxltszopxmtyioevrjovdhjjwblojltbgckf")
      tree.insert(92, 59, "ghgphrasqyxoxqhaangjduuulwzujwcptpafpifuxtcpvqohhl")
      tree.insert(56, 7, "rwbogskpcyujribqivyiupfopdwrsfzhdleninvrghihuydnhw")
      tree.insert(77, -86, "pibpbsmcxtoarxagkxwxhecrmrkidhyixxfotfjtxyahuevlxg")
      tree.insert(88, 75, "bpocbwmsjjgguomhhjywroyqihsdhdoduffnidysbcaopdxlnt")
      tree.insert(30, 32, "qokclegnyuxapbeszbnabnshusyjayqcxdmxlwtcdkhdthnpbh")
      tree.insert(26, -86, "xauczpkuufuolytpwqxopeoqhyndczbafmsgrqqatugfjybdlu")
      tree.insert(-17, -64, "yozfphnzcbhwyuaevuowoendugwzlkmffqvbhsohoqgtdomtlc")
      tree.insert(51, 45, "hywimidegrxfnzrutiixqkbvwxfgiodtxzsitcqlsfxnwqinxj")
      tree.insert(50, 41, "raqshbyfkcphzgngyyrhvyeocueevgyjgvjollrlveelgxplvn")
      tree.insert(5, -31, "fgdpxsaxjqcsqbxqgxkgrmnqfmhjbvecpqqsxktwvuindwutoy")
      tree.insert(5, -54, "ujzwrpdmsktktbrvgsbtkefygalmqrbosvhvyjenqebyimxkgw")
      tree.insert(-61, -10, "dwcwdrdjlcnooelvbbnpwhfgymbowrlkdcassbyxqimmzfxtbt")
      tree.insert(3, 30, "xylmoxflupgnpuamfruhghibwkcgjohuvvlozmrljzqzwyjhap")
      tree.insert(-95, 39, "wsmtdlezqyiruaenbttqqxsqoroonackmcfnmlpbblxafjgjwk")
      tree.insert(90, -8, "xyocaeokvpxfutlhbmhlwhjefqghpyzqobsltoyetkwjdeqmdc")
      tree.insert(-62, -52, "ajhyaojokejmqclfmzvxqgvhkfnxxynczeridwxqnkvpvrjiap")
      tree.insert(83, 0, "qfpyrvzsvizpujdzjncnhmnbymyvoumdtvkzosxweeghtyjvda")
      tree.insert(-74, 44, "vpblodqlwapytbhlumvourqbhvfodvlkthnhyfnzqhoqzisjju")
      tree.insert(-67, 78, "bfnupnipgiffdrnwrieyubxegnagocldaziwejnaxgxeobhcmm")
      tree.insert(-6, -40, "wtoxebhqvukmmckvbkhntqzvaiqlgjiwxgyajkrsyngwzamymf")
      tree.insert(-26, 91, "segjjkdjsszktpfneqqrzltdkabumkqsxuflnqggguqmxheqlo")
      tree.insert(71, -80, "cvriawpzpedchtacrarsrygqctfnqeaugxiylwimnjlbylsksp")
      tree.insert(-96, -50, "eidqgypguwqnrzefflhcrfzfnyixcnyfapronxwdvzeubhggil")
      tree.insert(16, 44, "wydcfedbgimoassugeklusmgubrwgzqtqcfzpynacvtmmycasf")
      tree.insert(-7, -8, "inttzzggerfyceesnhnykxlirnmzstcnuplrzvsasryrikcbzi")
      tree.insert(-22, 86, "lpdebrpbhgwzupusgoxjvnauitgibjwsykbrzvkholwgrkynwn")
      tree.insert(94, -12, "wqnwolksyhdwpyfdzrxrzkaljvekjqvpuwafplqrceijxpcroa")
      tree.insert(50, -5, "lbrebajdykkzsolcclgjystjrumkedbcvogauyiidwhusollix")
      tree.insert(-49, -30, "xovvpgqaykjoxoqxjzsinyfsvmgxuvlvqitgcukfawqxgeqvji")
      tree.insert(-89, -14, "bwguwjpomygjwqfhsxtytwkttxvhtwyneyfjymowydwrodzxhs")
      tree.insert(42, 48, "ufpmiyzbqhjdvhjpknkjiudnsezxyzjujmkjitelberevsvxzt")
      tree.insert(-91, 74, "jkujtxuwraexjcnffjawwvknexndiuodfkeyrfzpsoifkeumlf")
      tree.insert(58, -30, "wopgbrbtlikkxofzbklrnfytknnhsqzildtqdhnwoucfgsfgcm")
      tree.insert(54, -3, "pujtjpbtuuxtnewcchulddgetinvxvbnkstvyxxmslezlaqdxz")
      tree.insert(-82, 93, "pjnqmyroopsrbtssahwqrgzpeupjkyjwmxayhveomvfzmjyirm")
      tree.insert(76, 54, "gbsmjwbohcerzfawrazpzloaogqhpyfqbllsycexugpmxzwmty")
      tree.insert(68, 77, "gpxnhrymnqsiwtsxkmgbrnhtpbwklyksjzypmejxlqtfwedcgb")
      tree.insert(-78, -27, "pismiljgupqrcpqdoklnvzzcettmfjormheufdulknagiehtsq")
      tree.insert(-94, -95, "qejrrvanuwckwpqgjymgtjbpyaodjfsqkgqvbnuhongazfqjwa")
      tree.insert(29, -79, "nqmhfteenxkdomllwhfjlcfxotrzgadntqmlcvsnxlfyllraln")
      tree.insert(5, -20, "ezpxgoohhqhmjdkwdejricavedhseehpiukdwhflwuypceypem")
      tree.insert(-79, -28, "firejdtxatctwqofjgvqzeypmazewpfwruvpidnluxrxuzqjnd")
      tree.insert(36, -11, "idodxgcslfozzbxyhiesljieenbflpsrbpcwqfotpqomnngrmq")
      tree.insert(67, -10, "fofiokgmrcmdlkycplkonwryoujcpkwvcpnmtsnerrbxpdciom")
      tree.insert(-49, 32, "gxmgridhkkpvlsclbuhmshhxelotudqboltnfjpeexlrgsldek")
      tree.insert(-3, 20, "phcqoumxkokendflaxeqwutxkcshsteaybuwyyezwmslaknmqb")
      tree.insert(1, 26, "nebxdaegkpdgskjgcwdoyqodopndzxsgreunfubnxixiiytzwa")
      tree.insert(13, -76, "xvvldrjtqdhfumvpucrnatgrmvnjadprkgbmtmpgpdojeuvnxe")
      tree.insert(41, -4, "amorihrwljjgtjxgjbqnrttbtofeddnrpbywjpwkhczziaaiax")
      tree.insert(11, -98, "jobvzzwuqbrphtziyvzcufdnfvohcqtkpxdfizaxhqjutpasoo")
      tree.insert(8, 3, "xqhvvyzwnfarbrfgmrdzdgeiorggpfgdepobjnqvaxxrtoppxa")
      tree.insert(-59, -29, "ocficuvjyxwzupqyazegmjozkpbdaisfpbrjxsefgoauhwtoci")
      tree.insert(-94, -93, "kafcvruajhszcyoauuhkmzvorzxlhvyyzrhaasfokrhzsqrcwa")
      tree.insert(-58, 30, "ayjszmlbveonrdtdydpuljnfbykphfiuxsoojnsooxhyfwmoks")
      tree.insert(-42, -50, "tbmzwnwnoczaopaebzbbmefhkzeoigokpwjlsixaygajdymfte")
      tree.insert(48, 64, "uvfiqmznsbcyiarpvbbscfjtckgjkxcorveunvguhofutoubdk")
      tree.insert(-45, 61, "qtrosvhpppcrekkdavmmeqrkpzgrcauzuwrkvijpwuidnjnewd")
      tree.insert(-61, -87, "gqudtgmalenbthygihaxxfjjcvkaglswcyhvifsgvbtrcdgwbv")
      tree.insert(-50, 66, "tmoktmalcegojukpmpqmnbgzyxnkxgptcjvucqjudrbagzrugy")
      tree.insert(92, -92, "tzdfgbxvkzppbcwzdxhetbjjjmumypfjbzebdkalkpbeydwult")
      tree.insert(-96, 98, "hcxoughchknqmobifbzcffqdfhtgsasyarcbsercsesbckbpin")
      tree.insert(6, -25, "ueirbffosahlhswfoqqzzrnxfexnxnheflbyqshcxfwfvgmtnr")
      tree.insert(-12, -59, "zqoxysfbinrxgaewgiiwasytjeanlamrkocdqdvrrcrhntjrwo")
      tree.insert(21, 32, "brghduhcdyagtfcxjpizlhpmgrparkgvfmujyfcvjiesvobvnk")
      tree.insert(-17, -80, "dobxzbhcvdbwkfjoxckjzmvrcpakdvbxizoebwwzcuvmhjlraj")
      tree.insert(-59, -27, "gzvnmkccqxwacoixvwvnujrgzvenqbiveeyipshdfusybsgtjk")
      tree.insert(14, -68, "bftxsrseupzucqjmdhtmpkwjzlmjyhenaemnruojvbqhioaxdk")
      tree.insert(44, -3, "zptqwpovnzwjbfmmnbzfcnrrhgpupcjyowbgqlhdlkbkkjbvry")
      tree.insert(-48, 89, "yhcigklmbkancqzxbsbylskmmbzmxhcfmcewegddrpqeyxltst")
      tree.insert(12, 24, "kigjvdoqyahzakxsctkhgwuuwncschzawwugvamozqbiegmokm")
      tree.insert(-19, -37, "elchbfoukhywjmifbyjgmmrzxdskjjgaezoqcgylhggtixjnsb")
      tree.delete(-5, -84)
      tree.delete(68, 4)
      tree.delete(-61, 8)
      tree.insert(-24, -10, "htjuddwijnttnnbtxgcrbgqppcxhmfrgbpbxzrypidbvbdvozz")
      tree.insert(16, 72, "wqhrygjmuksvpjvtfwjrflxvqzqofcqvzvphjeigckfmlepbpw")
      tree.insert(-21, 16, "fukuwqnnnawcoxvkebynnsuspmqodolnicveaifoqqlsmforii")
      tree.insert(-5, 2, "wdgkfkyxwwiqvbqvbundehqjgmwtfutebekvtgzjdkuhwiozva")
      tree.insert(-12, 68, "nqglyhwajvralnofarmqemltfgbdgwfhogcxmogbfsuwyvflsu")
      tree.insert(100, -20, "jeateubqqviwekldtxirqisrgodsxhtsyooyuavmjjgiqeluoy")
      tree.delete(50, -5)
      tree.insert(73, -78, "ftiswugqihmgofvdecsugwnptiljfqhrzlayhkojpivmpprwiz")
      tree.insert(-85, 89, "mangmeonmoegbebgtdfjcgnoisdnqgutqweimrrlstbovtemey")
      tree.insert(-1, -99, "lfxpaomzgtbupbolokycvehmgauisvieewehyhizeulplmomld")
      tree.delete(-82, 93)
      tree.delete(-1, 74)
      tree.delete(47, -19)
      tree.insert(26, 6, "rlhxsegzzhukxymshlxkielynqkiobbymglmyjwwkqdycwlcuq")
      tree.delete(-82, -83)
      tree.delete(12, 24)
      tree.delete(-6, -40)
      tree.insert(-85, -29, "buntljjsfhpeuegvntucflmafuztueogzovnokorubzasjyayb")
      tree.delete(-7, -8)
      tree.delete(-26, 91)
      tree.insert(-66, -94, "hvhcnjlrguvopuzawwstplixokcbskjxnaizmgqrjzxeihrcax")
      tree.delete(-24, -10)
      tree.delete(93, -4)
      tree.insert(-73, -56, "cdwnclwmsdxywaxedchvhcjaztvvsiuzurhnlzkvrzxmohqemw")
      tree.insert(62, 68, "nxoafkzgqbgeclgtiigrdujuydqygwqrwajpgaerubsdudzeoo")
      tree.delete(-89, -14)
      tree.delete(76, 54)
      tree.delete(3, -26)
      tree.insert(50, -56, "ndbgaxzxohoyxsiuhlsulfdpfksijstlncpigunohfujmjvqge")
      tree.insert(33, -35, "pbhlpoejreygcybuyyyuswsmqgsvrljujeiodnklpfvlamajql")
      tree.delete(88, -81)
      tree.delete(6, -25)
      tree.insert(29, -48, "wcceipvigogmmomxvtxqbomkutskrxsmjfkecveuuwmpscbydi")
      tree.insert(99, 11, "tlxksjedhrbdediyobytipbaqvnrzemydpduvegaurzjktwuws")
      tree.insert(65, 70, "gjkqdvbqrpmduwylrpaxfjhxjjkguqtpfpomikusfcdvilrrth")
      tree.delete(98, -29)
      tree.insert(49, -63, "smgckwgipfmsodejjpouwkwsnqtwfgoicbqorwltsllwadnkec")
      tree.insert(51, -100, "aaiimwnomryfodcvamntwjjfwwlmctdovciromdfuckffadpyd")
      tree.delete(-96, 98)
      tree.delete(-61, -87)
      tree.delete(54, -3)
      tree.insert(77, -98, "yyodnjelximyzgureypgnqybyatulkhlkjiftjmtwlzbhonpuj")
      tree.delete(14, -68)
      tree.insert(29, -90, "jhlswifcywuomgtotklflqiramflqkqlsrhbcoeqytijmuzhca")
      tree.delete(16, 72)
      tree.delete(-19, -37)
      tree.insert(63, -83, "rheemfvuogrvfvphrldfvigthmcbsvojxktewmxwwafvgyripw")
      tree.insert(5, 47, "sqwjjxdmsmnttmtlnpnyvotmuxxzltxgmhbnejzsyvqtdyvyoq")
      tree.delete(99, 11)
      tree.delete(5, -54)
      tree.delete(74, -73)
      tree.insert(-5, 37, "iszmggqheszcprdbepuuvbscnnsfdbnfsddsrcrotaltdhieye")
      tree.delete(36, -11)
      tree.delete(5, -20)
      tree.delete(-58, -69)
      tree.insert(-82, -33, "eavjqmjnpeinizaddjellufvupzvuwzphqviohiyolsxvkxnbd")
      tree.insert(82, -90, "cabidhrmeqfkjxpfahggtfdgnxqiicykqgepuxtxuhdujfgmvo")
      tree.delete(30, 32)
      tree.delete(5, 47)
      tree.delete(-34, 17)
      tree.insert(-62, 8, "yvxexewuuzqnawnghzvmkhfyebgsljqxxveccljlkvujivxgdt")
      tree.insert(-1, 67, "kxcwuknsqycwxnfqfuynayeptxviwkkvqzbflftvgklvfriaic")
      tree.insert(-60, 52, "zctqfbwlbwsftcwtfrgafvrjiqnsdjvkllwfyjgiwtmwpasjko")
      tree.delete(-3, 20)
      tree.insert(85, -24, "paprgxvwrsvinvirndanuniaqopqifjzmuwmyyzvnwtlsquzxz")
      tree.insert(50, 18, "jmnclpoftygovwkpjztahtmicxrcxtvqzylryggzyliemalchh")
      tree.insert(-39, 72, "bozdkpzpbaytmaefrgtgbljblxfgkdlomtdkrfqundgvjouulm")
      tree.insert(-6, 13, "ayjrkimhphvvqcbnonqpbrcjdbgatkewwoinnznjfejyzbitqt")
      tree.insert(-13, -46, "hbrstiwlvgzmcakczzgclmzplqefypbomzssbepprzkzodjhbm")
      tree.delete(65, 70)
      tree.insert(-42, 26, "gslafhyssbkirktfcbtbalnabjsndecwsunmwtbfaylwlljdye")
      tree.delete(29, -48)
      tree.delete(-22, 86)
      tree.insert(35, 89, "wxkonuanyqkyqiwpyjuxgeolmyfdtnghbedmndotwcqolmvbpl")
      tree.insert(-44, -8, "yttjftuufnvrhgjfdpvlmhsaxalkgcundvsyilqprrgxrcxfux")
      tree.insert(25, -15, "bqlvdvirkjwrbbwboyfuzrvxpaavmpjvntlpypvnnsswnejeyk")
      tree.insert(-58, -94, "wuhpkmhbvtsacuiyigyuawcpscnoqcmxfujjebxjkqdmpplewn")
      tree.delete(-59, -27)
      tree.delete(68, 77)
      tree.insert(42, -5, "uckvslgtxcxoknesqwdvqbugntmcgwtkljtlpzpapzlcfvoirk")
      tree.delete(-62, 8)
      tree.insert(-61, 100, "jnmlelfwlnrihpvhiiudwnmvwlfycburtqocjzvqcanpkzvpaf")
      tree.delete(-1, 67)
      tree.insert(27, -53, "qxvvfylmgovamxgotggpojvtbusrngddcgckdzvgnqihpwtkgm")
      tree.delete(27, -53)
      tree.delete(50, -56)
      tree.delete(3, 30)
      tree.delete(71, -80)
      tree.insert(-41, 46, "xcqszgpufvkyjdhvexwznwlivjosalpamzjljjulzargwxsvyx")
      tree.delete(85, -24)
      tree.insert(15, 30, "zspumkucisydgvbjnvsxnmkhlddnrlhnfsqpaktpvmtizggeus")
      tree.delete(-44, -8)
      tree.delete(-4, -32)
      tree.delete(-12, -59)
      tree.insert(-74, -14, "jyqvmpehwmijubqholtvzwqdapzapbudfvzjhrvndwcnwlodio")
      tree.delete(21, 32)
      tree.insert(14, -10, "ihomokvxipweubwueewtfsnfbtngonszjfkwtarrqudqoszjrm")
      tree.delete(-17, -64)
      tree.delete(15, 30)
      tree.delete(-32, -16)
      tree.delete(25, -15)
      tree.delete(29, -90)
      tree.insert(-22, 46, "minymbjjecxmjmcnorryndwseaaujwlfnahudwstgzoqltnxsi")
      tree.delete(-5, 37)
      tree.insert(-25, -9, "qhmjtvcxrxifskueddloongejgxrjdpbpvdnyakchwqdjxheun")
      tree.delete(88, 75)
      tree.delete(73, -78)
      tree.delete(63, -83)
      tree.delete(51, -100)
      tree.delete(-66, -94)
      tree.delete(-91, 74)
      tree.insert(73, 76, "zzypcmrvhruaarppjppevwzrhhxfioebqwgwqhzcqzfikiowqm")
      tree.insert(59, 58, "qxxiiiphaysubnegswnfcllqlgsgoxddiljssnwrvpptjhgsga")
      tree.insert(-29, 66, "ejbdmwrqikiumwkdmpqtnrylcakjykrdllziwnudgcqaafezbj")
      tree.delete(14, -10)
      tree.delete(25, -71)
      tree.insert(87, 8, "jyacnxpblassyvzxmaetzkkztrplbxrpuyafhabhsyfqkvfoxw")
      tree.delete(-95, 39)
      tree.insert(-60, 32, "cigkyxsgwoihnelivkomxerggixgusznpvbdliyvujgmkwgmwh")
      tree.delete(58, -30)
      tree.insert(-4, -25, "rrgmigpbqkygpqpsbkmveagojflmboqggxhkiqavjabluavbrb")
      tree.delete(42, -5)
      tree.delete(-79, -28)
      tree.delete(-5, 2)
      tree.delete(-59, -29)
      tree.delete(-58, -94)
      tree.delete(-22, 46)
      tree.delete(1, 26)
      tree.delete(77, -98)
      tree.insert(22, -52, "fbybalhwbhofopxffluiseogkngcmrqmkehmodixhlypzwuzaa")
      tree.insert(8, 84, "vvnntnotbqszlaybantypqpwzyyfsrlbhcsuodnieuimvwicnq")
      tree.insert(27, -20, "etyceqlieqsszktmrqatkdkjayormkpgmwlsdrxpfdjphttzjh")
      tree.insert(56, 25, "efuocpduclquueswhkpmpipgybmfbjtkiqimkksgjoshhcouou")
      tree.insert(-7, 7, "rmdkjohyojwnzjpwhrttzlnglpwvdhnudotddpqnlsqrxtlpzy")
      tree.insert(-25, -12, "vjbvyhmnkrbuxiwpabjtishzcysxtnfiykfamqofachbeqgfmy")
      tree.insert(-83, 58, "oyvxnlgyeqdbnokrwqifftlhxazjpwacxdpcormvnjyurhhljv")
      tree.delete(-60, 32)
      tree.insert(-77, 0, "fseasbhuhhpczwhcouupfhjdbwhgyekwaphcofrusxubkrrxnq")
      tree.insert(-72, 41, "qxxunbpimkpzgmbherogaiykzbhqytckhrfkijiwhqcbnmvzsj")
      tree.delete(94, -12)
      tree.delete(33, -35)
      tree.insert(-30, 10, "gggvckxrvahpiivvimktnkrfmsgpodbemobvindhmonyhmtdiw")
      tree.insert(-49, -25, "pejohjtadzpnitmknqkrigglkpuldtkfrpbebzuijematbpwbm")
      tree.insert(82, -85, "exikziyuozsfjbjvrnrxlaszlmnigpofjaxycfrdwtqpswsmqp")
      tree.insert(-10, 23, "nwindhobcsmcooebpxqmuhzcuiyrypakojsrfdctmvhhgwvgtd")
      tree.insert(-59, 9, "sqczbukibyujqeiinlnhyrwtzqlieopqgeycicumefcqcsfmvw")
      tree.insert(43, -26, "pwbdksdtoajqfcypatykqtcjaevnqbjnahfivbzmjrpaagjmiu")
      tree.insert(-63, 63, "fvvdueqjbbmgqbornngrbajskoqsxdesopuzrdaxuicjjunaqb")
      tree.delete(-96, -50)
      tree.insert(-21, 79, "hhdrbltnmiyqverpfsixccnabwrqvhopmqntrfowmsjairmali")
      tree.insert(69, 100, "yvbohciriidhhwrlqtthqagvdzvdkwuxaxifmwqwfqkvozjzxk")
      tree.insert(-64, 95, "jbfxjsdziaxxmzvopswhkbslitmopajlvnftklskjfiafwtzrv")
      tree.insert(78, 91, "vscnihfacbahcwgkpdeybhedzbdpabdijrcoauadlxqmvsdmky")
      tree.delete(53, -54)
      tree.insert(8, 60, "fpmjarbsswzukqfulntwrqbjsepdkgkmvyivtegazkzflylsyz")
      tree.delete(-61, 100)
      tree.insert(-78, 69, "fuezkmxfnjldcckskcnvcbhjxnycpknubtkundswocqbkrzllv")
      tree.insert(-50, 63, "vqsezlwqcppmhlxofwhrnasepqemleilhnkaziknobotszvilk")
      tree.insert(-92, 82, "dcqhipwkpkzcutokldsmgykqrtradlvsmmrqdehntbzbzvdvfi")
      tree.delete(92, 59)
      tree.delete(8, 60)
      tree.delete(35, 89)
      tree.delete(87, 8)
      tree.delete(-42, -50)
      tree.delete(-95, 59)
      tree.insert(46, 46, "totyxsemjuitjrcrgrorqigoouflzwxtrwhpnpkcsdoaxqfiot")
      tree.delete(51, 45)
      tree.insert(56, -33, "manpmnewdazmzjwqafzflxhbubyxssyzujlcozlaxxeowgscjy")
      tree.insert(-16, 37, "krppxtktkzptyxoxoyzhujhcvwtkzuqyjvgkqlxegmqbfpxxoz")
      tree.delete(-94, -95)
      tree.insert(90, 84, "jddyjevwemkrkyrphtrqahjrzvaanekbdfxnxyymjcajvmggmp")
      tree.insert(73, -68, "jiroimzfacalhxluyiuftwkevtfwvnvcneaubmtigcvwvuaenv")
      tree.insert(36, -17, "gueezvoccxianlkobefzyudgfwxxluvgrqjslmhwxdqlgjibij")
      tree.insert(29, -98, "lmfnukcakratcnjmklmmfrylndluhjrxyxrstaeldxitayxuig")
      tree.delete(-10, 23)
      tree.delete(43, -26)
      tree.insert(-16, -55, "zsnirijjwynptaosqckcsjuwkzylpmklxvycomphljpocebqkc")
      tree.insert(59, 69, "yvdcwtuaksltcncytmvwowmkmjdawfrefsqqrcapykxflwinnz")
      tree.insert(5, -88, "tpjootjpdztgpmpbpzcmhhcvvzbmkmteyljnailiqxohdrsork")
      tree.delete(90, 84)
      tree.delete(-99, 24)
      tree.insert(76, 0, "owbwnqcyuufzfdniffixselegxhelwaniyeafkarhnuwbnjewi")
      tree.delete(-82, -33)
      tree.insert(-76, -19, "hbikyfjcukuqamsooehjwrlgpolyppcbrdkkpuasaueovhouji")
      tree.insert(31, 11, "nvuxbgqjkxwzwdbzhevzdugqveovfxhyhyrqnrcubuodpjchde")
      tree.insert(74, -75, "qkjbugbgivujmxxpqvpplvjotnjmepzeiustjeyzngfjrzpezs")
      tree.delete(73, 76)
      tree.delete(62, 68)
      tree.delete(31, 11)
      tree.delete(26, -86)
      tree.insert(-64, 77, "tijuzmpirmkpiuxphhwbpctccjdvzzrzbtmdclrjpaoslknpua")
      tree.insert(-15, 62, "midmrfgruriowlkiinrdstritmejynyknylsfrcvvzxeckqdad")
      tree.delete(-1, -99)
      tree.delete(-73, -56)
      tree.delete(11, -98)
      tree.insert(57, -81, "wtnejjsvahhqcxxsfhryxfctwimgiblsjewlnzblrsasphykkc")
      tree.insert(61, -14, "gzlqyrkmlkpnyymqcydgrsjkwcrdjdlswqdwytehdkpvvesjse")
      tree.insert(63, -49, "trlwhidcrntzxcghzdrndmpmmwopnshniixkmuexyynwfytkff")
      tree.insert(98, 6, "ynouaeguolubgjwvxuiinoztyqjegmdufiinpewwmaqwxqgqin")
      tree.delete(29, -79)
      tree.insert(-83, -97, "dfdeghxnsexyztlsgbbafqemhytesoptbwmlhabgqkquiingko")
      tree.delete(29, -98)
      tree.delete(8, 84)
      tree.insert(-51, -78, "mdjdvmtvmgcbyentswabenwjoiqmwkbkxitlvynnqzeanspahu")
      tree.delete(-30, 10)
      tree.insert(57, 19, "qiwmihjhxgyqqmdhzsnddvcgcirtjjftojaigarqfltnwtalxz")
      tree.delete(-77, 67)
      tree.delete(56, 7)
      tree.delete(60, 15)
      tree.insert(-55, -37, "qnplgijgtzrjsrjaffpvrodeedzbgrnvhfesbixizhndvdatkd")
      tree.insert(-83, 82, "qzcmuiubmqslhxmgnhwvnptzimujzkxkhzsgsmedwpltjocdha")
      tree.insert(20, -53, "itosctuqfzswknflohglvtrfeqmpnlatljbgutkpejmdqbpxup")
      tree.delete(-77, 0)
      tree.delete(90, -40)
      tree.delete(83, 0)
      tree.delete(56, -33)
      tree.insert(91, -77, "ppixuihhopdhpxzpejnieyuvkguxmgtwapnsqxmlnddvcqbxsc")
      tree.delete(38, -44)
      tree.delete(-50, 66)
      tree.delete(-85, 89)
      tree.delete(-42, 26)
      tree.delete(-64, 95)
      tree.insert(48, -92, "ghqztrblvssjnmhxfrndhxcshzqhfidxparpbmdyebbldheewg")
      tree.delete(100, -20)
      tree.insert(59, -45, "fvngwhgacsllldiuhrfjmmxopobqxhgbxcbzjhwgfewdhzfwyi")
      tree.insert(52, 90, "xmkntunqhykqxrdmstjsasheddxmnhpchwkiqgkziepdzfbzjf")
      tree.insert(71, -41, "rreenhfvhvtawyqohftmnyxgmifrrnumbyulsvfavzrvyltuhc")
      tree.delete(-76, -19)
      tree.delete(50, 41)
      tree.insert(-66, -81, "halvahjzpvsofbfclyjezrllyanjatowrsgvhmsymgwoogmxtn")
      tree.delete(63, -49)
      tree.insert(70, -21, "tdgxizyvzphjwidsmfxjpajrfzwdnocxupsqgxhnljvyanrthu")
      tree.insert(34, -85, "xfgodevqoyhavsvoglfdktygjtgklmuhecjbxmgecjvrgbesnd")
      tree.insert(-67, 66, "artrjgbwuazzvktjjwngbrsuebqflombnddfgzvaxuwuhtzpil")
      tree.insert(32, -7, "gftzrnlciijnlqmtlwbzxiunewuxkujixcimwhnzumthwvngop")
      tree.insert(-58, 15, "nztmdcqgbsnoczhyquinzfmhrihsnkoynlbpwaqzjuwaabvinq")
      tree.insert(-70, 33, "woktmkenaouxstxeyfslxqhgdqmoyhgnwljimgpddekaefwtxj")
      tree.insert(47, 6, "yhdyxzsspbiysoqhhegzifjqjdcrbwgmecsiuollnforumjmwh")
      tree.delete(26, 6)
      tree.insert(-8, -15, "ducjcldmvypzneqqxtxtiqetrkcvvwyepltalznngxhnhtzkpm")
      tree.delete(69, -1)
      tree.delete(-6, 13)
      tree.insert(3, -53, "mrpboyvydhjwlkisjipydwbkvyelpiwkswvkcaaxuhcddmlfuz")
      tree.insert(-15, -9, "ouhixnlecpwnvlaldcdvnzeugvvgjjbszyeonthpksszrajfuf")
      tree.insert(76, -66, "qfhtlkaluawrgyyeluevjjypdewmmgfbzhbbgtrjyongtmdyml")
      tree.delete(-67, 78)
      tree.delete(61, -14)
      tree.insert(61, 97, "ujjntcjggfqyalcvatfsjrlrxmfamzrehcxgepnuvviqptwuzr")
      tree.insert(21, 78, "efghoizzkolpcmpaybhhfeqxikazygbreaoztkqjkkuzrcaekw")
      tree.insert(-79, 24, "fddkyweyxzyprzunjtkunxyjabktywpixqqyofsiiisplfxixq")
      tree.delete(-49, 32)
      tree.delete(-88, 40)
      tree.delete(-25, -9)
      tree.insert(63, -57, "zuuuhhejoncrfgwqmvnweksmizbiumoouqeezjkkozlwgsgiqj")
      tree.insert(-18, 27, "wtuofillrrrvzrgmhoyqfgurpviqwzaazftpnvnqmxjkztsmtr")
      tree.delete(91, -77)
      tree.insert(36, -92, "wxekdxetundkgiuqgwjlnjnxaaokauqginnhqwhgnuvwvpxdhk")
      tree.delete(-94, -93)
      tree.delete(-72, 41)
      tree.delete(69, 100)
      tree.insert(-5, -13, "mdspsczpbsknopzqivcfxmcexwvbpbeoexshslojrjfdtnqsuz")
      tree.insert(6, 52, "sfyskkoufghsnaomjpmhmpxpfsnnjdpaniaructkkcvdkqyese")
      tree.insert(2, -44, "jwuqztzaudomujawbtitpvyhvpbmuhmeddamuwyxqkohaearqa")
      tree.delete(-59, 9)
      tree.delete(98, 6)
      tree.insert(0, 10, "ffypvvoexydccdcmkorzraovhnrbrzbvqfdjckbznbfctfnprx")
      tree.insert(41, 98, "fylstbvoxtporufewhzhotovgpfwyjoygadmfylxrikdqkdzna")
      tree.delete(-67, 66)
      tree.insert(17, 100, "xxgzrgrtfclfkhknarmkjsbvcwiwwrvrvlrjpbzoqthwepakbs")
      tree.delete(32, -86)
      tree.delete(57, 19)
      tree.insert(14, 75, "nvftolejzmztnqqzpwumcosvbiuisvbtnhzcsonmltgqsyzkkg")
      tree.delete(8, 3)
      tree.delete(76, 0)
      tree.insert(59, -64, "xmobrdzwudjzmkdncjcmzhkihypsoiejypshxpydreppkfrobq")
      tree.delete(-15, 62)
      tree.insert(28, -16, "uovfeyfgdblrqlqynkzggutftsbncozskssuepnjjhkjluvpjf")
      tree.delete(-21, -55)
      tree.delete(16, 44)
      tree.delete(59, -64)
      tree.delete(92, -92)
      tree.insert(-8, -5, "jpewwjdywkunsbjnzzlxmmnucowwkumuvvietkfjsjlmshvsvs")
      tree.insert(-72, 68, "vejolicahzpnyuwtdojgamknjgrtvrkcbwchveflyqklfoavjn")
      tree.delete(61, 97)
      tree.delete(20, -53)
      tree.insert(-14, 36, "tkhayfqdpitfqrekpysvxbwuknleieoqrsnjfxuowzauodanve")
      tree.insert(-97, -64, "piphlivbqpmdizvlgpezyfjvxrdwfejclupirfwvtqzouetjan")
      tree.delete(52, 90)
      tree.delete(-12, 68)
      tree.delete(77, -86)
      tree.insert(-5, -81, "kwevnthghnrogtcrqffibpxjhelitvizyozqkllcrylwwqkkes")
      tree.insert(-71, -92, "uswlhcycswezztdgovoygroskevgjschizeqfwuxiyrgylazku")
      tree.delete(90, -8)
      tree.insert(-68, 26, "myxbcvxhrfcbbggeodketkwbozbuvmxpwhorgctzqkplaysntp")
      tree.insert(-96, 37, "xymakuiycxjjmzkidqldqbhujlcjpjvtwajcjnkikaahbgwrmu")
      tree.delete(-4, 60)
      tree.insert(67, 74, "ezsyaxwabrdqaitpuulqaqxjxqkuahsvpzgszucnwwvbifoqqj")
      tree.delete(-58, 15)
      tree.insert(23, -11, "eoqzaxxiylcekqknvbehdvubkpzhyupjkpsyrkvpyzmqcssfcf")
      tree.insert(-45, -12, "utobkkhxtgywmkybsvyiielpxacrzgwrbunjvffekicypujesp")
      tree.insert(-49, -46, "iftlyoixonraciotspftavxpbxyhohiuevkcudmorainvfhipr")
      tree.delete(-39, 72)
      tree.insert(-80, -40, "riwreehkmzfneoubccrtipjdlouahlhcamrzsvcgvbafbrbxfj")
      tree.insert(-2, 11, "fuxbzaskhlgukjfjhvgozouswaeazsfqggjwqvwtfaragcheau")
      tree.delete(-45, -12)
      tree.delete(50, 18)
      tree.delete(67, -10)
      tree.delete(-55, -37)
      tree.delete(-78, 69)
      tree.insert(-97, -55, "sfcnsedqpbfjsmdpjremhaqgzpdnfiitquojigkafdjenvykrg")
      tree.insert(-74, -62, "hdyqhdsalflayeacklyzzcvrlkouxrussixegljvfxerdmfosh")
      tree.delete(-29, 66)
      tree.delete(34, -85)
      tree.insert(-57, -55, "qistblalnymufkowbzhjhaxqyxeusesltcpaphlgsmqoxkdvdf")
      tree.insert(-92, 47, "tjjpilchfvqjniwrdosovsfhnikybenoufjjlfpbfxdqailsli")
      tree.delete(76, -66)
      tree.insert(98, -96, "bxjvpmgwwsfdrjluppazgzvdzpioakoezvtayfnokwjxskuphb")
      tree.insert(-27, -24, "zspmigtwfptwzyatowuodqrdeyzermvvolyrvnydhmgzhtnick")
      tree.delete(6, 52)
      tree.insert(-73, -32, "kywgvvihubufobpozjuspkewqxoivqtqdslohtexqkrqnmuyft")
      tree.insert(21, -54, "gdkxgodzlqgxixfteyglumxiyxlnpoprtmmxioetmjmneoefzs")
      tree.delete(74, -75)
      tree.insert(45, -73, "nvbnnnxqfwaqkwozmmoyfkljxakrtcypcnxgmlmwgkpgbolxey")
      tree.insert(-68, -52, "uouressrxycwzntfxusribweeyaliwuozubwgzolfklzebusmr")
      tree.insert(34, 51, "udmksdrqitopnoaoajmoxfihftzxvxbymbuklvqwtzkpmhjgqr")
      tree.delete(59, 69)
      tree.insert(-19, 27, "veukawdtqeqhhuzlgnawojgrrmxbtcptzoidqueflyyibnlsmi")
      tree.delete(48, 64)
      tree.insert(58, 58, "bxwynjbhzclwxwtkcknywbfcwqbdexzvsfngdsqeirbpaqzftx")
      tree.insert(29, 11, "ulbjkzcyxphthlxbvwohipjtcjertefydjwjqpewvxlklxminm")
      tree.insert(15, 4, "qzamgykrtzgjzpaljooyjcfcpujtlwodtrcfcsntodypimjxpb")
      tree.delete(-83, 82)
      tree.insert(73, 4, "oxzoeidjiezxleexicltvnvkgsnmxrgrsplyvilfqxhsngfqci")
      tree.delete(58, 58)
      tree.delete(-18, 27)
      tree.insert(13, -56, "htzogpznadscthbfvydhewftosqkegpdpkveutahejhbssfigv")
      tree.delete(47, 6)
      tree.insert(38, 33, "cyaakznebuyantkinkkbcmnvkxouagzfpglapfwsuldphlszis")
      tree.delete(59, -45)
      tree.insert(33, -83, "qzzvzzxbzyvwnazyfvsauaaprtcujycvrhgyvexmyaafwkepzb")
      tree.insert(10, -18, "qnyoctsqhrprkerdqnttdtqcxtczcnmvhqjexddcysfxobjhpf")
      tree.insert(67, -49, "cjquajsxwakskiljbnfpeifzbjvgljoyrlvmiqqodstcyhdpjc")
      tree.delete(-71, -92)
      tree.delete(-96, 37)
      tree.insert(57, 77, "euvojfugmvizbbgpkqaqciivohnwspxehfdnriwcykqdlqscqw")
      tree.insert(-12, -47, "tmrvxfeiowukesqutmibkfeiumudqureygmovtscosvyppmmae")
      tree.delete(5, -88)
      tree.delete(-83, 58)
      tree.insert(-52, -71, "twwoxpkenelhnnalsruaszaznwzlduvqhqevdchdjzkrseqfjn")
      tree.insert(96, 89, "edirmlbfgiaoqcjccjqnsjxrrzglqxkzbufiriqindysctvrjp")
      tree.insert(-5, -42, "jpratrhkhbgyllfoobulvohjkcocbnmvwcnlaejqaskbrokvms")
      tree.insert(79, 6, "pagoefuvpjihbgounbzfnxmsuzjdjbwbhqjwvrtpzkqqeipcuk")
      tree.delete(73, -68)
      tree.insert(-65, 20, "cybalyyqoahuihpbldukddntalcfymasfsmylipfmsdsgvabab")
      tree.delete(42, 48)
      tree.delete(-97, -55)
      tree.delete(21, -54)
      tree.insert(-83, 73, "vbeqodchvvpuerlrgbazyrxtflesrjtzrtlspahposbgdugulb")
      tree.delete(67, 74)
      tree.insert(-78, 18, "iftkiwctabmqowuggsvybeyxkfmhmzyzzxrnossdbfphiuzwbc")
      tree.delete(-61, -10)
      tree.delete(36, -17)
      tree.delete(-74, -14)
      tree.insert(-67, -76, "ypjltsjerrivebabmjfcwbmxrsjbkjgvixkuxuvypuevekuwgh")
      tree.insert(-58, 31, "lfadzagkvehxxaercrdluwuqbxbbsmgpncjnrffjyjqbonrdxe")
      tree.delete(-5, -42)
      tree.delete(57, 77)
      tree.delete(-74, -62) // REBUILDS HERE
      tree.insert(-66, -17, "wabserharfmmmgsbeythsicctjhhijcjykqwowmldnvmybpcjw")
      tree.insert(-16, 13, "aoxbhctxsxhbwxyfdkztxcwpuxbyjldprnnyjkynetwlahkfvr")
      tree.delete(-80, -40)
      tree.insert(43, 21, "vcdfvlpvghkokzoskwqbzoaonghfggufsvvyzdbksshrxejsxd")
      tree.insert(-9, 63, "ucjcgwommvzhsjzajznkradprpblyjdwzmfipgdhitxmypzrsw")
      tree.insert(91, -52, "vecojaqnhwexobujmzwuxeociczcjquuowgohkxprolruinwpc")
      tree.insert(-17, -75, "fybutxcpeqtsbzdampcowiwlsbfydpojohbnucbdsgzzwwikqr")
      tree.delete(-19, 27)
      tree.delete(-12, -47)
      tree.delete(41, -4)
      tree.insert(10, 19, "pzhfawuvqaqugvtxobxowyabaqucjebpkuranilvuppjhahsrl")
      tree.delete(-16, 13)
      tree.insert(-87, -96, "ocjyqbdovveueemoygnmlzogxxkjtxjgkdpbqpxcbqhipesaar")
      tree.insert(62, -8, "tvugdrkwpyqwgsjrixprlvmsqxajgdhbkfdgpkafmtctuicyut")
      tree.insert(-35, 47, "lwkwetolfylmohveemufzfsqabkcmlaqmjcwggvmwezfehnveo")
      tree.delete(-14, 36)
      tree.delete(-8, -15)
      tree.delete(14, 75)
      tree.delete(15, 4)
      tree.delete(-68, -52)
      tree.delete(44, -3)
      tree.delete(29, 11)
      tree.insert(-43, -5, "rjnoenwkjguisypxmntxireromwkjsbfgcrlxiaaydvrvxhzko")
      tree.delete(-83, -97)
      tree.insert(82, -22, "kzxyelzocfvqozhqppbgxxbojjocathtpqatvuygeljwbaxwaz")
      tree.delete(-21, 79)
      tree.delete(38, 33)
      tree.insert(-52, 76, "obhxoyzncczwsffjrulawlbthcwnrgrgogthutpxxkykcvonpx")
      tree.insert(54, 84, "sdinbvjxssftcbdboetyrtoybobyrdkwzzpaxptdjqlmbobbcq")
      tree.delete(-13, -46)
      tree.delete(-58, 31)
      tree.delete(-17, -80)
      tree.delete(13, -56)
      tree.delete(63, -57)
      tree.delete(41, 98)

      assertTrue(tree.delete(13, -76))
   }
}